### ISSUE TITLE
项目为何不能运行

### ISSUE THREAD

**Issue by WangShang1** [yingLanNull/ScrollLayout#1]
![image](https://cloud.githubusercontent.com/assets/18344354/17767875/615cfb62-6564-11e6-9ff3-595367392f0c.png)

**Comment by yingLanNull** [comment]
已修复，可再次下载测试

**Comment by yingLanNull** [comment]
已修复，请再次下载测试 @WangShang1

**Comment by WangShang1** [comment]
ok了 谢谢
