### ISSUE TITLE
1

### ISSUE THREAD

**Issue by gincoo** [yingLanNull/ScrollLayout#10]

**Comment by yingLanNull** [comment]
理论应该是可以的，我到目前没有测试过使用Fragment，如果你已经测试有什么问题可以反馈结果到这里，共同优化使用，谢谢

**Comment by gincoo** [comment]
我想在Scrolllayout 里套ContentScrollView  嵌套TabLayout +ViewPager +fragment
现在fragment高度已经设置了match_parent，并且因为Scrollview嵌套viewpager所以重写了ViewPager。这个fragment不能完全展开。我现在还在找原因中。在看你的源码

**Comment by yingLanNull** [comment]
ScrollView嵌套ViewPager本身会有显示不全的问题，既然你已经重写了ViewPager，请问你给ContentScrollView设置属性android:fillViewport=”true”了吗

**Comment by gincoo** [comment]
ok了，忘记设置了！谢谢！！很棒！

**Comment by gincoo** [comment]
如果能给tabLayout添加顶部粘粘效果就更好了
