### ISSUE TITLE
在scrollview里面嵌套tablayout+viewpager后

### ISSUE THREAD

**Issue by gincoo** [yingLanNull/ScrollLayout#12]
在scrollview里面嵌套tablayout+viewpager后,viewpager中的每个fragment的高度 现在是以fragment中最高的那个来定了。导致我的某个fragment本身没有这么高，已经到底部了，但是还是可以滑动到更底的地方如何处理？目前项目有些紧，能否告知一下还有什么控件可以实现3段滑动效果。算法有些看不懂，想移植到coodinlayout里面 的behaviour不会移植。好难受卡着了

**Comment by yingLanNull** [comment]
有，但能不能满足你需求不太肯定，可以试试这个[AndroidSlidingUpPanel](https://github.com/umano/AndroidSlidingUpPanel)。另外你结合我的库使用的的ViewPager的高度，我个人认为应该是滑到每个pager页都应该重新计算一边高度，推荐[博文](http://blog.csdn.net/qq_34972666/article/details/52386999?locationNum=11)。

**Comment by gincoo** [comment]
感谢！每页面的确要重新计算高度，并且我添加了占位的view。防止透底。我想在非scrolllayout区域控制滑动关联scorlllayout，背景是一张图片，通过设置图片的onTouchListener监听，想直接传递scorll_layout.onTouchEvent(event)  ，但是不行，还在想办法
