### ISSUE TITLE
您好 我把布局放在地图上会出现花屏

### ISSUE THREAD

**Issue by tutuoo** [yingLanNull/ScrollLayout#15]
我点击搜索,然后回调回地图页面的时候  地图会花屏 是什么原因啊~~好急啊~~

**Comment by yingLanNull** [comment]
你确定是布局引起的花屏吗

**Comment by tutuoo** [comment]
不,不不,     我已经解决了   是因为搜索栏弹出来的软键盘导致的  谢谢啦~~
