### ISSUE TITLE
请问scrollLayout位于最底部状态时底部的高度如何改变

### ISSUE THREAD

**Issue by WangShang1** [yingLanNull/ScrollLayout#2]
![image](https://cloud.githubusercontent.com/assets/18344354/17804658/3d063c1c-662f-11e6-903e-26ba016b16b7.png)
我想把这个高度设低一点 应该改什么，谢谢

**Comment by yingLanNull** [comment]
```
    app:exitOffset="**dp"
```

或
       mScrollLayout.setExitOffset()

**Comment by OnlyKang** [comment]
如果ListView的数据只有一两条，我只想完全显示出ListView的数据
