### ISSUE TITLE
中途停顿的时候，我想只滑动listview该怎么改呢？

### ISSUE THREAD

**Issue by houpe** [yingLanNull/ScrollLayout#3]
中途停顿的时候，我想只滑动listview该怎么改呢？
当listview滑动到底的时候，在滑动scroll，可以给点思路么？

**Comment by yingLanNull** [comment]
scrolllayout并不是能看见的部分那样大小，只是竖向移动了，底部看不见的区域还是有内容的，如果要修改可能不止一点改动，方向的话就是尝试从scrolllayout的touch事件上和配套的ContentListView滚动下功夫

**Comment by houpe** [comment]
好的 谢谢 我尝试下吧
