### ISSUE TITLE
第二个页面好像和高德不一样

### ISSUE THREAD

**Issue by GuoZhaoHui628** [yingLanNull/ScrollLayout#4]
你好，还在维护这个库吗，第二个页面貌似和高德不一样，不知道能不能改成如高德商家详情样的

**Comment by yingLanNull** [comment]
@GuoZhaoHui628 最近没有关注这个了，库的描述与现在新版的高德地图样式确实不一致，谢谢你的提出，有时间的话我会根据你建议尝试更新该库。

**Comment by GuoZhaoHui628** [comment]
大佬你好，没想到还在关心这个库，我主要想问下，在scrollview中怎样监听下拉切换界面的事件，有时间可以说下 吗

**Comment by yingLanNull** [comment]
目前有一个OnScrollProgressListener，里面有各种状态和滑动时参数的监听，DEMO里面有使用，不清楚是不是你需要的。

**Comment by GuoZhaoHui628** [comment]
ok，好的 ，谢谢了
